# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { 
      device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=25%" "mode=755" ];
    };

  fileSystems."/boot" =
    { 
      device = "/dev/disk/by-uuid/3048-0EF1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "umask=0077" ];
    };

  fileSystems."/nix" =
    { 
      device = "/dev/disk/by-uuid/1970ba22-80d4-4796-9c4a-45a292df28aa";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:1" "noatime" ];
    };

  fileSystems."/persistent" =
    { 
      device = "/dev/disk/by-uuid/1970ba22-80d4-4796-9c4a-45a292df28aa";
      neededForBoot = true;
      fsType = "btrfs";
      options = [ "subvol=@persistent" "compress=zstd:1" "noatime" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/f70d4ff2-8b6a-45b9-b548-628969158c81"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
